#define ZDEL_HINT_QUEUE 0
#define ZDEL_HINT_LETMELIVE 1
#define ZDEL_HINT_IWILLGC 2
#define ZDEL_HINT_HARDDEL 3
#define ZDEL_HINT_HARDDEL_NOW 4

#define GC_QUEUE_FILTER 1
#define GC_QUEUE_CHECK 2
#define GC_QUEUE_HARDDELETE 3
#define GC_QUEUE_COUNT 3

#define GC_FILTER_QUEUE 2
#define GC_CHECK_QUEUE 2//(1 SECONDS)
#define GC_DEL_QUEUE 2
//ZDEL É ZANEQUINHA DELETE